### PR TITLE
added settings screen

### PR DESCRIPTION
**Pull request by mansiPaTeLL**
Part of #208.

@holtzmak @MummenRider @SanaKhan1997 Please review the <SettingScreen>. This can be accessed from every page from now. 

image

### CODE REVIEW

**Comment by holtzmak** [comment]
@mansiPaTeLL Do the other screens still have the <- button in the app bar?

**Review by holtzmak — CHANGES_REQUESTED** [review]
You appear to have this in the Active, History, and Home screens but not ALL screens. 
I think it would suffice to have this just on the Home Screen.

- [x] In addition, could you add the <- back button into the app bar? 
> Then it would follow the pattern we have for other screens that don't have a bottom nav bar (we can here because there's just one item).

- [x] Could you space the buttons like the Home Screen? The two close buttons seem strange.

**Comment by mansiPaTeLL** [comment]
> You appear to have this in the Active, History, and Home screens but not ALL screens.
> I think it would suffice to have this just on the Home Screen.

@holtzmak I think We should keep on Active, History, and Home screen. We might not need it on Editing Screens.  I have added it on Account Screen though. We also not need it on Authentication pages obviously.

**Comment by mansiPaTeLL** [comment]
@holtzmak Please review the requested changes.

**Review by holtzmak — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
