### PR TITLE
Update pre-commit-config for Dart and Flutter, remove python

### PR DESCRIPTION
**Pull request by holtzmak**
Part of #73 (not complete). Added Flutter and dart linters, we have kotlin and java already as part of the android package. 

What else should be added that we'll change? Maybe swift files?

### CODE REVIEW

**Comment by holtzmak** [comment]
@MummenRider I'll play around with GitHub actions and run all our brand new Flutter code once the structure is merged. Maybe bump Mansi and Sana about another review from one of them...?

**Comment by MummenRider** [comment]
> @MummenRider I'll play around with GitHub actions and run all our brand new Flutter code once the structure is merged. Maybe bump Mansi and Sana about another review from one of them...?

I pm'd both of them this afternoon and hoping to get it review soon

**Review by MummenRider — APPROVED** [review]
All changes looks good

**Comment by holtzmak** [comment]
FYI I'm sneaking in the reformatting into this PR as well - Don't bother reviewing the changes as they're all going to be format, whitespace, etc. minor changes.

**Review by holtzmak — COMMENTED** [review]
Don't need the explicit dart formatter because the dart SDK is like a sub-SDK of the Flutter SDK, and Flutter uses `dartfmt` on it's own with `Flutter format .`

**Pull request merged**
