### PR TITLE
Gui changes

### LINKED ISSUE #214: Update application GUI with a proper color theme
- [x] Update the GUI and it's components to look better

### PR DESCRIPTION
**Pull request by SanaKhan1997**
Screenshot_1615764990
Screenshot_1615764996
Screenshot_1615765001
Screenshot_1615765017
Screenshot_1615765021
Screenshot_1615765026
Screenshot_1615765087
Screenshot_1615765114
Screenshot_1615765117

### CODE REVIEW

**Comment by SanaKhan1997** [comment]
You might notice the Back button label in bottom nav bar is blue that is because for some weird reason I can't figure it out

**Comment by holtzmak** [comment]
@SanaKhan1997 Were you able to fix the bottom nav bar thing?

Also, the bottom nav bar button text is still grey:
Screen Shot 2021-03-14 at 10 54 00 PM

This could use more space between the text and the button:
Screen Shot 2021-03-14 at 10 53 36 PM

Also, how does the `ATREditingScreen` look when the forms are expanded? And how does the `AccountEditingScreen` look?

Maybe another PR is needed to address the editing form appearance.

**Comment by SanaKhan1997** [comment]
> @SanaKhan1997 Were you able to fix the bottom nav bar thing?
> 
> Also, the bottom nav bar button text is still grey:
> Screen Shot 2021-03-14 at 10 54 00 PM
> 
> This could use more space between the text and the button:
> Screen Shot 2021-03-14 at 10 53 36 PM
> 
> Also, how does the `ATREditingScreen` look when the forms are expanded? And how does the `AccountEditingScreen` look?
> 
> Maybe another PR is needed to address the editing form appearance


Capture

**Review by MummenRider — APPROVED** [review]
LGTM

**Review by holtzmak — APPROVED** [review]
Thanks for making those minor changes. It looks like the Email Form and ATR Editing screen still need some love. The email form can be updates as part of #201 and I can update the editing screen.

**Pull request merged**
