### PR TITLE
Import Kotlin Multiplatform Mobile project and run pre-commit hooks

### LINKED ISSUE #26: Investigate (and create) cross-platform agnostic GUI code
Investigate how to write/get working the cross-platform (agnostic) GUI code:
1. Start investigating Kotlin's cross-platforming https://kotlinlang.org/lp/mobile/ 
1. Could start a Wiki page with the options cross-platform code could be written
1. Get a window running on android and iOS (this is expected to be a dummy window, if you write the "real-thing" we could also merge into our codebase!)
1. Investigate different GUI libraries for cross-platform Kotlin (if we aren't constrained by the API)*

*Kotlin works with all Java code, so we can investigate Java GUI libraries like JavaFX and Java Swing. To avoid overhead of JavaFX we could use TornadoFx (Kotlin wrapper library) instead, for example.
 
See the above notes to determine how to move forward.

### PR DESCRIPTION
**Pull request by holtzmak**
Closes #26 once complete and tested on windows, or will directly close regardless of review if #33 goes ahead instead.

**If we want to really go with KMM**, still need to do:

- [ ] Wiki page with IDE config instructions (will be a little lengthy, but should be a one-time configuration)

### CODE REVIEW

**Comment by holtzmak** [comment]
@MummenRider lemme know if you want a walk-through review on this one, typically we wouldn't make a PR this huge, but there's no way around it for the project base.

**Comment by holtzmak** [comment]
Further notes:
1. This runs with JDK 14, SDK Android 29, Gradle 6.6.1 for building, and older gradle tools 3.5.2 (because we use AndroidX which relies on this)
2. This has been tested on mac so far with the Google Pixel 3A ("Hello World") and iPhone 11 (No base app, but project compiles and an empty app icon appears due to `dummyFile`)

 _I've personally not worked with Swift before so I made no "Hello World" app in Swift, but can do so if we're moving forward with KMM_

**Comment by MummenRider** [comment]
LGTM

**Review by MummenRider — APPROVED** [review]
LGTM

**Comment by holtzmak** [comment]
Closing this PR as per #33 - we'll be using Flutter, which is similar but with better support. Uses the dart language over kotlin.

**Pull request closed without merging**
