### PR TITLE
Splash screen

### LINKED ISSUE #150: Create the Splash screen when first opening the app
- [x] Add the splash screen as per our Hi-Fi design

This screen will show up while the application hooks up the Firebase service, etc. Talk to @MummenRider about this screen, as he already had some work done for it in #95 .

### PR DESCRIPTION
**Pull request by SanaKhan1997**
I've added app icon and splash screen. Feel free to recommend changes for app icon(background color, design) since it will only take few minutes to apply these changes. Also I haven't applied the logic to check if user is logged in, it will go in splash screen view model.

### CODE REVIEW

**Comment by SanaKhan1997** [comment]
splash_app_icon

**Comment by holtzmak** [comment]
@SanaKhan1997 @MummenRider @mansiPaTeLL are we going with green for the app? What about the colors for website, muted browns and greys with accent green?

I am thinking splash screen is hard on the eyes. I wouldn't mind just a green circular outline around the icon and then white or off-white around it.

**Comment by SanaKhan1997** [comment]
> @SanaKhan1997 @MummenRider @mansiPaTeLL are we going with green for the app?

I wasn't sure but if people want I can make color changes throughout the app so that we have consistent color theme. TBH I kinda want different color from green.

**Comment by holtzmak** [comment]
I was thinking icon was busy, too. How about this?
110287922-dfc0f780-7fac-11eb-8cfa-b22ae294cbfb

**Comment by MummenRider** [comment]
Yea, we can stick to green and maybe add accent to it
> @SanaKhan1997 @MummenRider @mansiPaTeLL are we going with green for the app? What about the colors for website, muted browns and greys with accent green?
> 
> I am thinking splash screen is hard on the eyes. I wouldn't mind just a green circular outline around the icon and then white or off-white around it.

**Comment by mansiPaTeLL** [comment]
@SanaKhan1997 @holtzmak @MummenRider We can choose some color themes and according to that we can change it. I can even do into our prototypes if you guys and can decide what color scheme will be best and then we can into our app.

**Comment by SanaKhan1997** [comment]
image

**Review by holtzmak — APPROVED** [review]
LGTM! Colour choice changes can/will be made later.

**Pull request merged**
