### PR TITLE
cleaned up image-picker screen

### LINKED ISSUE #202: Bring back ImagePicker/Screen
This screen should be able to be launched from AccountEditing and ATREditing screens.

- [x] Ensure the image picker/camera gallery picker is called when editing and choosing to add or change a photo.
- [x] Ensure the file or filename is indeed passed on after being chosen

This work goes in hand with the tasks #215 and #199 and #207

### PR DESCRIPTION
**Pull request by mansiPaTeLL**
@holtzmak @MummenRider Please review the image-picker screen. 

https://user-images.githubusercontent.com/44125953/112959383-99b90880-9100-11eb-83eb-ce285d933d62.mov

### CODE REVIEW

**Comment by mansiPaTeLL** [comment]
#202

**Comment by holtzmak** [comment]
Wow, this cleaned up nice. I'll try this out on my machine later today. Thanks!

**Comment by holtzmak** [comment]
I see this error if I don't pick an image and go back. You should handle the possible return of a null file or similar.

In addition, you should handle what happens if someone hits the back button on android (skipper get image like the above). You can use `WillPopScope` like the `ATREditingScreen` to get control.
```
E/StorageException( 1311): StorageException has occurred.
E/StorageException( 1311): Object does not exist at location.
E/StorageException( 1311):  Code: -13010 HttpResult: 404
E/StorageException( 1311): {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException( 1311): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException( 1311): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:434)
E/StorageException( 1311): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:451)
E/StorageException( 1311): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:442)
E/StorageException( 1311): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException( 1311): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:286)
E/StorageException( 1311): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:70)
E/StorageException( 1311): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:62)
E/StorageException( 1311): 	at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:76)
E/StorageException( 1311): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException( 1311): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException( 1311): 	at java.lang.Thread.run(Thread.java:919)
```

**Review by holtzmak — CHANGES_REQUESTED** [review]
- [x] You should use the `NavigatorService` in this file instead of `Navigator.of(context)`

I think we should combine some more what Clark has in the `AccountEditingViewModel` and this screen. Maybe we don't need a screen at all, this can just be a widget we use where needed.

**Comment by mansiPaTeLL** [comment]
@holtzmak Thanks Kelly for helping me out with this PR. :)

**Review by holtzmak — APPROVED** [review]
Good to go now!

**Pull request merged**
