### PR TITLE
Add files via upload

### LINKED ISSUE #6: Start Project Charter
Fill out out sections that we have information, now, on.
1. Create documentation folder in code and put Project Charter PDF in it (submit for PR review)
2. Create additional tasks for sections that need more information i.e.: Project Specification

### PR DESCRIPTION
**Pull request by SanaKhan1997**
Project docs folder

### CODE REVIEW

**Comment by holtzmak** [comment]
One minor comment as we can't see the PDF due to it not being a code or txt file (we obviously don't want it to be): please change the folder `Documentation` to `documentation`. The lowercase name is the standard for folder names.

**Comment by holtzmak** [comment]
> One minor comment as we can't see the PDF due to it not being a code or txt file (we obviously don't want it to be): please change the folder `Documentation` to `documentation`. The lowercase name is the standard for folder names.

Update: We can view the PDF by going to "Files Changed" and then right clicking the menu on the Project Charter PDF (The three dots) and selecting "view file". I think we should remove Tim's name from the charter and just state Project Supervisor... What do you think?

**Comment by SanaKhan1997** [comment]
> > One minor comment as we can't see the PDF due to it not being a code or txt file (we obviously don't want it to be): please change the folder `Documentation` to `documentation`. The lowercase name is the standard for folder names.
> 
> Update: We can view the PDF by going to "Files Changed" and then right clicking the menu on the Project Charter PDF (The three dots) and selecting "view file". I think we should remove Tim's name from the charter and just state Project Supervisor... What do you think?

Alright we can replace it with Capstone Supervisor but stating the name with role is also not wrong. But yeah I think rather than name mentioning his role (Project Supervisor) is more important

**Comment by SanaKhan1997** [comment]
> One minor comment as we can't see the PDF due to it not being a code or txt file (we obviously don't want it to be): please change the folder `Documentation` to `documentation`. The lowercase name is the standard for folder names.

done

**Comment by holtzmak** [comment]
> > > One minor comment as we can't see the PDF due to it not being a code or txt file (we obviously don't want it to be): please change the folder `Documentation` to `documentation`. The lowercase name is the standard for folder names.
> > 
> > 
> > Update: We can view the PDF by going to "Files Changed" and then right clicking the menu on the Project Charter PDF (The three dots) and selecting "view file". I think we should remove Tim's name from the charter and just state Project Supervisor... What do you think?
> 
> Alright we can replace it with Capstone Supervisor but stating the name with role is also not wrong. But yeah I think rather than name mentioning his role (Project Supervisor) is more important

I think I'd mentioned previously about us keeping identifiable/personal information out of the repository. With only our information, interested people will be forced to contact us. We also may not have permission for what's posted for identifiable information on the repo.

**Review by holtzmak — APPROVED** [review]
This is a good first run of the Project Charter. Some things referenced like the "retrievable database" need further definition (which we'll get to in the future). Thanks!

**Comment by holtzmak** [comment]
Oh, please also link the Project Charter in the "About the Project Charter" Wiki page once this is merged, if you haven't decided to do so already.

**Pull request merged**
