### PR TITLE
Add the Transfer of Care UJMs

### LINKED ISSUE #51: Create the Transfer of Care UJMs from USMs
Using the USM from #44, create the corresponding User Journey Maps (UJMs) using the structure from #47.

You'll likely notice that the UJM structure doesn't match what you see the UJM as, so if we need to make changes to the GUI structure, talk to the assignee of #47.

### PR DESCRIPTION
**Pull request by holtzmak**
A first draft of the Transfer of Care stories, in UJM form to discover landing pages in the application and what the transporter needs from the pages. Close #51 .

### CODE REVIEW

**Comment by holtzmak** [comment]
This is in draft right now as I generate the other UJMs, the interesting files for review in this PR are ones like [this](https://github.com/holtzmak/Humane-Transport/pull/58/files#diff-6b7494c5c6fadda6f70ee28e0ef391068a18742356aaba80b282fe589539438b). Includes minor cleanup as we commit PDFs to the codebase (in the future we'll likely not want documentation in the codebase... Wonder what's best to do? The site and wiki work well but they don't have the capability to store PDFs for the future).

**Comment by holtzmak** [comment]
Added all ToC stories, not including story where no special even happens as it can be seen from the overlap in the UJMs now what occurs in the normal case of animal transfer of care. Ready for review.

**Review by MummenRider — COMMENTED** [review]
Everything looks good. I love the persona logos, it looks clean and professional. 
One thing I noticed about nngoup template is it lacks of visualization of user's emotion as it go through different journeys. This is mainly because the template are just texts.

**Comment by SanaKhan1997** [comment]
I noticed few things in ToC UJMs:

1. Receiver rejects delivery UJM( Under scenario you mentioned consignee rejected delivery which should be Receiver)
2. Forms are selected as phases(phases usually focus on user's flow of action in process instead of product elements as phase i.e ATR, FWR, CP and ToC). What you have is more similar to user experience map
3. Just a suggestion: We should have a document describing personas and organizations such as:

> Shipper: organization responsible for supplying animals(owners)

> Consignee: organization responsible for shipping

> Receiver: organization receiving the delivery of animals

**Comment by holtzmak** [comment]
@SanaKhan1997 [Saw your last PR](https://github.com/holtzmak/Humane-Transport/pull/60#pullrequestreview-530816903) and will change my UJMs accordingly for your points 1 and 2.

Created #61 as per point 3.

**Comment by holtzmak** [comment]
> Everything looks good. I love the persona logos, it looks clean and professional.
> One thing I noticed about nngoup template is it lacks of visualization of user's emotion as it go through different journeys. This is mainly because the template are just texts.

What's your suggestion for emphasizing emotion? I find that the UJMs allow us to write what the transporter is doing/thinking/saying. It probably would be excess effort at this time to make empathy maps.

**Comment by holtzmak** [comment]
@SanaKhan1997 and @MummenRider ready for re-review

**Comment by MummenRider** [comment]
> > Everything looks good. I love the persona logos, it looks clean and professional.
> > One thing I noticed about nngoup template is it lacks of visualization of user's emotion as it go through different journeys. This is mainly because the template are just texts.
> 
> What's your suggestion for emphasizing emotion? I find that the UJMs allow us to write what the transporter is doing/thinking/saying. It probably would be excess effort at this time to make empathy maps.

By using this template you really can't emphasize emotion of the user. Unless you put lines(represents emotion) on the template, which will look bad because it will overlap with the text. If we value the "time" more, then I think this is the best template for UJM.

**Comment by SanaKhan1997** [comment]
> @SanaKhan1997 and @MummenRider ready for re-review

Thanks! They look good.

**Comment by holtzmak** [comment]
> > @SanaKhan1997 and @MummenRider ready for re-review
> 
> Thanks! They look good.

Need approval if it looks good :)

**Review by SanaKhan1997 — APPROVED** [review]

**Pull request merged**
